version: 3
endpoint: http://graphql-engine:8080
metadata_directory: ./db/metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
migrations_directory: ./db/migrations
seeds_directory: ./db/seeds
